{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "pS-wkv9JdiZh"
   },
   "source": [
    "# Credit Risk Resampling Techniques"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {
    "id": "B7UN-IMkdiZj"
   },
   "outputs": [],
   "source": [
    "import warnings\n",
    "warnings.filterwarnings('ignore')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {
    "id": "QeRFFNn5diZu"
   },
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import pandas as pd\n",
    "from pathlib import Path\n",
    "from collections import Counter"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "4NWwfw5IdiZ0"
   },
   "source": [
    "# Read the CSV and Perform Basic Data Cleaning"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {
    "id": "qQmZ00f5diZ3"
   },
   "outputs": [],
   "source": [
    "columns = [\n",
    "    \"loan_amnt\", \"int_rate\", \"installment\", \"home_ownership\",\n",
    "    \"annual_inc\", \"verification_status\", \"issue_d\", \"loan_status\",\n",
    "    \"pymnt_plan\", \"dti\", \"delinq_2yrs\", \"inq_last_6mths\",\n",
    "    \"open_acc\", \"pub_rec\", \"revol_bal\", \"total_acc\",\n",
    "    \"initial_list_status\", \"out_prncp\", \"out_prncp_inv\", \"total_pymnt\",\n",
    "    \"total_pymnt_inv\", \"total_rec_prncp\", \"total_rec_int\", \"total_rec_late_fee\",\n",
    "    \"recoveries\", \"collection_recovery_fee\", \"last_pymnt_amnt\", \"next_pymnt_d\",\n",
    "    \"collections_12_mths_ex_med\", \"policy_code\", \"application_type\", \"acc_now_delinq\",\n",
    "    \"tot_coll_amt\", \"tot_cur_bal\", \"open_acc_6m\", \"open_act_il\",\n",
    "    \"open_il_12m\", \"open_il_24m\", \"mths_since_rcnt_il\", \"total_bal_il\",\n",
    "    \"il_util\", \"open_rv_12m\", \"open_rv_24m\", \"max_bal_bc\",\n",
    "    \"all_util\", \"total_rev_hi_lim\", \"inq_fi\", \"total_cu_tl\",\n",
    "    \"inq_last_12m\", \"acc_open_past_24mths\", \"avg_cur_bal\", \"bc_open_to_buy\",\n",
    "    \"bc_util\", \"chargeoff_within_12_mths\", \"delinq_amnt\", \"mo_sin_old_il_acct\",\n",
    "    \"mo_sin_old_rev_tl_op\", \"mo_sin_rcnt_rev_tl_op\", \"mo_sin_rcnt_tl\", \"mort_acc\",\n",
    "    \"mths_since_recent_bc\", \"mths_since_recent_inq\", \"num_accts_ever_120_pd\", \"num_actv_bc_tl\",\n",
    "    \"num_actv_rev_tl\", \"num_bc_sats\", \"num_bc_tl\", \"num_il_tl\",\n",
    "    \"num_op_rev_tl\", \"num_rev_accts\", \"num_rev_tl_bal_gt_0\",\n",
    "    \"num_sats\", \"num_tl_120dpd_2m\", \"num_tl_30dpd\", \"num_tl_90g_dpd_24m\",\n",
    "    \"num_tl_op_past_12m\", \"pct_tl_nvr_dlq\", \"percent_bc_gt_75\", \"pub_rec_bankruptcies\",\n",
    "    \"tax_liens\", \"tot_hi_cred_lim\", \"total_bal_ex_mort\", \"total_bc_limit\",\n",
    "    \"total_il_high_credit_limit\", \"hardship_flag\", \"debt_settlement_flag\"\n",
    "]\n",
    "\n",
    "target = [\"loan_status\"]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/",
     "height": 338
    },
    "id": "U9dE_rZudiZ9",
    "outputId": "57988ea9-78ff-49b8-a359-2cda45519b63"
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>loan_amnt</th>\n",
       "      <th>int_rate</th>\n",
       "      <th>installment</th>\n",
       "      <th>home_ownership</th>\n",
       "      <th>annual_inc</th>\n",
       "      <th>verification_status</th>\n",
       "      <th>issue_d</th>\n",
       "      <th>loan_status</th>\n",
       "      <th>pymnt_plan</th>\n",
       "      <th>dti</th>\n",
       "      <th>...</th>\n",
       "      <th>pct_tl_nvr_dlq</th>\n",
       "      <th>percent_bc_gt_75</th>\n",
       "      <th>pub_rec_bankruptcies</th>\n",
       "      <th>tax_liens</th>\n",
       "      <th>tot_hi_cred_lim</th>\n",
       "      <th>total_bal_ex_mort</th>\n",
       "      <th>total_bc_limit</th>\n",
       "      <th>total_il_high_credit_limit</th>\n",
       "      <th>hardship_flag</th>\n",
       "      <th>debt_settlement_flag</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>10500.0</td>\n",
       "      <td>0.1719</td>\n",
       "      <td>375.35</td>\n",
       "      <td>RENT</td>\n",
       "      <td>66000.0</td>\n",
       "      <td>Source Verified</td>\n",
       "      <td>Mar-2019</td>\n",
       "      <td>low_risk</td>\n",
       "      <td>n</td>\n",
       "      <td>27.24</td>\n",
       "      <td>...</td>\n",
       "      <td>85.7</td>\n",
       "      <td>100.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>65687.0</td>\n",
       "      <td>38199.0</td>\n",
       "      <td>2000.0</td>\n",
       "      <td>61987.0</td>\n",
       "      <td>N</td>\n",
       "      <td>N</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>25000.0</td>\n",
       "      <td>0.2000</td>\n",
       "      <td>929.09</td>\n",
       "      <td>MORTGAGE</td>\n",
       "      <td>105000.0</td>\n",
       "      <td>Verified</td>\n",
       "      <td>Mar-2019</td>\n",
       "      <td>low_risk</td>\n",
       "      <td>n</td>\n",
       "      <td>20.23</td>\n",
       "      <td>...</td>\n",
       "      <td>91.2</td>\n",
       "      <td>50.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>271427.0</td>\n",
       "      <td>60641.0</td>\n",
       "      <td>41200.0</td>\n",
       "      <td>49197.0</td>\n",
       "      <td>N</td>\n",
       "      <td>N</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>20000.0</td>\n",
       "      <td>0.2000</td>\n",
       "      <td>529.88</td>\n",
       "      <td>MORTGAGE</td>\n",
       "      <td>56000.0</td>\n",
       "      <td>Verified</td>\n",
       "      <td>Mar-2019</td>\n",
       "      <td>low_risk</td>\n",
       "      <td>n</td>\n",
       "      <td>24.26</td>\n",
       "      <td>...</td>\n",
       "      <td>66.7</td>\n",
       "      <td>50.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>60644.0</td>\n",
       "      <td>45684.0</td>\n",
       "      <td>7500.0</td>\n",
       "      <td>43144.0</td>\n",
       "      <td>N</td>\n",
       "      <td>N</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>10000.0</td>\n",
       "      <td>0.1640</td>\n",
       "      <td>353.55</td>\n",
       "      <td>RENT</td>\n",
       "      <td>92000.0</td>\n",
       "      <td>Verified</td>\n",
       "      <td>Mar-2019</td>\n",
       "      <td>low_risk</td>\n",
       "      <td>n</td>\n",
       "      <td>31.44</td>\n",
       "      <td>...</td>\n",
       "      <td>100.0</td>\n",
       "      <td>50.0</td>\n",
       "      <td>1.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>99506.0</td>\n",
       "      <td>68784.0</td>\n",
       "      <td>19700.0</td>\n",
       "      <td>76506.0</td>\n",
       "      <td>N</td>\n",
       "      <td>N</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>22000.0</td>\n",
       "      <td>0.1474</td>\n",
       "      <td>520.39</td>\n",
       "      <td>MORTGAGE</td>\n",
       "      <td>52000.0</td>\n",
       "      <td>Not Verified</td>\n",
       "      <td>Mar-2019</td>\n",
       "      <td>low_risk</td>\n",
       "      <td>n</td>\n",
       "      <td>18.76</td>\n",
       "      <td>...</td>\n",
       "      <td>100.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "      <td>219750.0</td>\n",
       "      <td>25919.0</td>\n",
       "      <td>27600.0</td>\n",
       "      <td>20000.0</td>\n",
       "      <td>N</td>\n",
       "      <td>N</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>5 rows Ã— 86 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "   loan_amnt  int_rate  installment home_ownership  annual_inc  \\\n",
       "0    10500.0    0.1719       375.35           RENT     66000.0   \n",
       "1    25000.0    0.2000       929.09       MORTGAGE    105000.0   \n",
       "2    20000.0    0.2000       529.88       MORTGAGE     56000.0   \n",
       "3    10000.0    0.1640       353.55           RENT     92000.0   \n",
       "4    22000.0    0.1474       520.39       MORTGAGE     52000.0   \n",
       "\n",
       "  verification_status   issue_d loan_status pymnt_plan    dti  ...  \\\n",
       "0     Source Verified  Mar-2019    low_risk          n  27.24  ...   \n",
       "1            Verified  Mar-2019    low_risk          n  20.23  ...   \n",
       "2            Verified  Mar-2019    low_risk          n  24.26  ...   \n",
       "3            Verified  Mar-2019    low_risk          n  31.44  ...   \n",
       "4        Not Verified  Mar-2019    low_risk          n  18.76  ...   \n",
       "\n",
       "   pct_tl_nvr_dlq  percent_bc_gt_75  pub_rec_bankruptcies  tax_liens  \\\n",
       "0            85.7             100.0                   0.0        0.0   \n",
       "1            91.2              50.0                   1.0        0.0   \n",
       "2            66.7              50.0                   0.0        0.0   \n",
       "3           100.0              50.0                   1.0        0.0   \n",
       "4           100.0               0.0                   0.0        0.0   \n",
       "\n",
       "   tot_hi_cred_lim  total_bal_ex_mort total_bc_limit  \\\n",
       "0          65687.0            38199.0         2000.0   \n",
       "1         271427.0            60641.0        41200.0   \n",
       "2          60644.0            45684.0         7500.0   \n",
       "3          99506.0            68784.0        19700.0   \n",
       "4         219750.0            25919.0        27600.0   \n",
       "\n",
       "   total_il_high_credit_limit  hardship_flag  debt_settlement_flag  \n",
       "0                     61987.0              N                     N  \n",
       "1                     49197.0              N                     N  \n",
       "2                     43144.0              N                     N  \n",
       "3                     76506.0              N                     N  \n",
       "4                     20000.0              N                     N  \n",
       "\n",
       "[5 rows x 86 columns]"
      ]
     },
     "execution_count": 4,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Load the data\n",
    "file_path = Path('LoanStats_2019Q1.csv')\n",
    "df = pd.read_csv(file_path, skiprows=1)[:-2]\n",
    "df = df.loc[:, columns].copy()\n",
    "\n",
    "# Drop the null columns where all values are null\n",
    "df = df.dropna(axis='columns', how='all')\n",
    "\n",
    "# Drop the null rows\n",
    "df = df.dropna()\n",
    "\n",
    "# Remove the `Issued` loan status\n",
    "issued_mask = df['loan_status'] != 'Issued'\n",
    "df = df.loc[issued_mask]\n",
    "\n",
    "# convert interest rate to numerical\n",
    "df['int_rate'] = df['int_rate'].str.replace('%', '')\n",
    "df['int_rate'] = df['int_rate'].astype('float') / 100\n",
    "\n",
    "\n",
    "# Convert the target column values to low_risk and high_risk based on their values\n",
    "x = {'Current': 'low_risk'}   \n",
    "df = df.replace(x)\n",
    "\n",
    "x = dict.fromkeys(['Late (31-120 days)', 'Late (16-30 days)', 'Default', 'In Grace Period'], 'high_risk')    \n",
    "df = df.replace(x)\n",
    "\n",
    "df.reset_index(inplace=True, drop=True)\n",
    "\n",
    "df.head()"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "0UVZH545diaD"
   },
   "source": [
    "# Split the Data into Training and Testing"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {
    "id": "2ZdNDsMDdiaE"
   },
   "outputs": [],
   "source": [
    "# Create our features\n",
    "X = df.drop(\"loan_status\", axis=1)\n",
    "# converting the string values under columns into # numerical ones using the get_dummies() method.\n",
    "X = pd.get_dummies(X)\n",
    "\n",
    "\n",
    "# Create our target\n",
    "y = df[[\"loan_status\"]]"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/",
     "height": 363
    },
    "id": "1a07gsk-diaM",
    "outputId": "ab6238d7-5caf-44d2-ad9d-5df8e2895f1e"
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>loan_amnt</th>\n",
       "      <th>int_rate</th>\n",
       "      <th>installment</th>\n",
       "      <th>annual_inc</th>\n",
       "      <th>dti</th>\n",
       "      <th>delinq_2yrs</th>\n",
       "      <th>inq_last_6mths</th>\n",
       "      <th>open_acc</th>\n",
       "      <th>pub_rec</th>\n",
       "      <th>revol_bal</th>\n",
       "      <th>...</th>\n",
       "      <th>issue_d_Mar-2019</th>\n",
       "      <th>pymnt_plan_n</th>\n",
       "      <th>initial_list_status_f</th>\n",
       "      <th>initial_list_status_w</th>\n",
       "      <th>next_pymnt_d_Apr-2019</th>\n",
       "      <th>next_pymnt_d_May-2019</th>\n",
       "      <th>application_type_Individual</th>\n",
       "      <th>application_type_Joint App</th>\n",
       "      <th>hardship_flag_N</th>\n",
       "      <th>debt_settlement_flag_N</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>count</th>\n",
       "      <td>68817.000000</td>\n",
       "      <td>68817.000000</td>\n",
       "      <td>68817.000000</td>\n",
       "      <td>6.881700e+04</td>\n",
       "      <td>68817.000000</td>\n",
       "      <td>68817.000000</td>\n",
       "      <td>68817.000000</td>\n",
       "      <td>68817.000000</td>\n",
       "      <td>68817.000000</td>\n",
       "      <td>68817.000000</td>\n",
       "      <td>...</td>\n",
       "      <td>68817.000000</td>\n",
       "      <td>68817.0</td>\n",
       "      <td>68817.000000</td>\n",
       "      <td>68817.000000</td>\n",
       "      <td>68817.000000</td>\n",
       "      <td>68817.000000</td>\n",
       "      <td>68817.000000</td>\n",
       "      <td>68817.000000</td>\n",
       "      <td>68817.0</td>\n",
       "      <td>68817.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>mean</th>\n",
       "      <td>16677.594562</td>\n",
       "      <td>0.127718</td>\n",
       "      <td>480.652863</td>\n",
       "      <td>8.821371e+04</td>\n",
       "      <td>21.778153</td>\n",
       "      <td>0.217766</td>\n",
       "      <td>0.497697</td>\n",
       "      <td>12.587340</td>\n",
       "      <td>0.126030</td>\n",
       "      <td>17604.142828</td>\n",
       "      <td>...</td>\n",
       "      <td>0.177238</td>\n",
       "      <td>1.0</td>\n",
       "      <td>0.123879</td>\n",
       "      <td>0.876121</td>\n",
       "      <td>0.383161</td>\n",
       "      <td>0.616839</td>\n",
       "      <td>0.860340</td>\n",
       "      <td>0.139660</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>std</th>\n",
       "      <td>10277.348590</td>\n",
       "      <td>0.048130</td>\n",
       "      <td>288.062432</td>\n",
       "      <td>1.155800e+05</td>\n",
       "      <td>20.199244</td>\n",
       "      <td>0.718367</td>\n",
       "      <td>0.758122</td>\n",
       "      <td>6.022869</td>\n",
       "      <td>0.336797</td>\n",
       "      <td>21835.880400</td>\n",
       "      <td>...</td>\n",
       "      <td>0.381873</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.329446</td>\n",
       "      <td>0.329446</td>\n",
       "      <td>0.486161</td>\n",
       "      <td>0.486161</td>\n",
       "      <td>0.346637</td>\n",
       "      <td>0.346637</td>\n",
       "      <td>0.0</td>\n",
       "      <td>0.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>min</th>\n",
       "      <td>1000.000000</td>\n",
       "      <td>0.060000</td>\n",
       "      <td>30.890000</td>\n",
       "      <td>4.000000e+01</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>2.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>...</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>1.0</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>25%</th>\n",
       "      <td>9000.000000</td>\n",
       "      <td>0.088100</td>\n",
       "      <td>265.730000</td>\n",
       "      <td>5.000000e+04</td>\n",
       "      <td>13.890000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>8.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>6293.000000</td>\n",
       "      <td>...</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>1.0</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>50%</th>\n",
       "      <td>15000.000000</td>\n",
       "      <td>0.118000</td>\n",
       "      <td>404.560000</td>\n",
       "      <td>7.300000e+04</td>\n",
       "      <td>19.760000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>11.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>12068.000000</td>\n",
       "      <td>...</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>1.0</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>75%</th>\n",
       "      <td>24000.000000</td>\n",
       "      <td>0.155700</td>\n",
       "      <td>648.100000</td>\n",
       "      <td>1.040000e+05</td>\n",
       "      <td>26.660000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>16.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>21735.000000</td>\n",
       "      <td>...</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>1.0</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1.0</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>max</th>\n",
       "      <td>40000.000000</td>\n",
       "      <td>0.308400</td>\n",
       "      <td>1676.230000</td>\n",
       "      <td>8.797500e+06</td>\n",
       "      <td>999.000000</td>\n",
       "      <td>18.000000</td>\n",
       "      <td>5.000000</td>\n",
       "      <td>72.000000</td>\n",
       "      <td>4.000000</td>\n",
       "      <td>587191.000000</td>\n",
       "      <td>...</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>1.0</td>\n",
       "      <td>1.0</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>8 rows Ã— 95 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "          loan_amnt      int_rate   installment    annual_inc           dti  \\\n",
       "count  68817.000000  68817.000000  68817.000000  6.881700e+04  68817.000000   \n",
       "mean   16677.594562      0.127718    480.652863  8.821371e+04     21.778153   \n",
       "std    10277.348590      0.048130    288.062432  1.155800e+05     20.199244   \n",
       "min     1000.000000      0.060000     30.890000  4.000000e+01      0.000000   \n",
       "25%     9000.000000      0.088100    265.730000  5.000000e+04     13.890000   \n",
       "50%    15000.000000      0.118000    404.560000  7.300000e+04     19.760000   \n",
       "75%    24000.000000      0.155700    648.100000  1.040000e+05     26.660000   \n",
       "max    40000.000000      0.308400   1676.230000  8.797500e+06    999.000000   \n",
       "\n",
       "        delinq_2yrs  inq_last_6mths      open_acc       pub_rec  \\\n",
       "count  68817.000000    68817.000000  68817.000000  68817.000000   \n",
       "mean       0.217766        0.497697     12.587340      0.126030   \n",
       "std        0.718367        0.758122      6.022869      0.336797   \n",
       "min        0.000000        0.000000      2.000000      0.000000   \n",
       "25%        0.000000        0.000000      8.000000      0.000000   \n",
       "50%        0.000000        0.000000     11.000000      0.000000   \n",
       "75%        0.000000        1.000000     16.000000      0.000000   \n",
       "max       18.000000        5.000000     72.000000      4.000000   \n",
       "\n",
       "           revol_bal  ...  issue_d_Mar-2019  pymnt_plan_n  \\\n",
       "count   68817.000000  ...      68817.000000       68817.0   \n",
       "mean    17604.142828  ...          0.177238           1.0   \n",
       "std     21835.880400  ...          0.381873           0.0   \n",
       "min         0.000000  ...          0.000000           1.0   \n",
       "25%      6293.000000  ...          0.000000           1.0   \n",
       "50%     12068.000000  ...          0.000000           1.0   \n",
       "75%     21735.000000  ...          0.000000           1.0   \n",
       "max    587191.000000  ...          1.000000           1.0   \n",
       "\n",
       "       initial_list_status_f  initial_list_status_w  next_pymnt_d_Apr-2019  \\\n",
       "count           68817.000000           68817.000000           68817.000000   \n",
       "mean                0.123879               0.876121               0.383161   \n",
       "std                 0.329446               0.329446               0.486161   \n",
       "min                 0.000000               0.000000               0.000000   \n",
       "25%                 0.000000               1.000000               0.000000   \n",
       "50%                 0.000000               1.000000               0.000000   \n",
       "75%                 0.000000               1.000000               1.000000   \n",
       "max                 1.000000               1.000000               1.000000   \n",
       "\n",
       "       next_pymnt_d_May-2019  application_type_Individual  \\\n",
       "count           68817.000000                 68817.000000   \n",
       "mean                0.616839                     0.860340   \n",
       "std                 0.486161                     0.346637   \n",
       "min                 0.000000                     0.000000   \n",
       "25%                 0.000000                     1.000000   \n",
       "50%                 1.000000                     1.000000   \n",
       "75%                 1.000000                     1.000000   \n",
       "max                 1.000000                     1.000000   \n",
       "\n",
       "       application_type_Joint App  hardship_flag_N  debt_settlement_flag_N  \n",
       "count                68817.000000          68817.0                 68817.0  \n",
       "mean                     0.139660              1.0                     1.0  \n",
       "std                      0.346637              0.0                     0.0  \n",
       "min                      0.000000              1.0                     1.0  \n",
       "25%                      0.000000              1.0                     1.0  \n",
       "50%                      0.000000              1.0                     1.0  \n",
       "75%                      0.000000              1.0                     1.0  \n",
       "max                      1.000000              1.0                     1.0  \n",
       "\n",
       "[8 rows x 95 columns]"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "X.describe()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/",
     "height": 68
    },
    "id": "hF44NzGydiaS",
    "outputId": "33f7c351-0f88-4f39-e962-6aceb5eb7ff6"
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "low_risk     68470\n",
       "high_risk      347\n",
       "Name: loan_status, dtype: int64"
      ]
     },
     "execution_count": 7,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Check the balance of our target values\n",
    "y['loan_status'].value_counts()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "metadata": {
    "id": "RjVSLvVLdiaa"
   },
   "outputs": [],
   "source": [
    "from sklearn.model_selection import train_test_split\n",
    "X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "Lvif39zwdiae"
   },
   "source": [
    "# Oversampling\n",
    "\n",
    "In this section, you will compare two oversampling algorithms to determine which algorithm results in the best performance. You will oversample the data using the naive random oversampling algorithm and the SMOTE algorithm. For each algorithm, be sure to complete the folliowing steps:\n",
    "\n",
    "1. View the count of the target classes using `Counter` from the collections library. \n",
    "3. Use the resampled data to train a logistic regression model.\n",
    "3. Calculate the balanced accuracy score from sklearn.metrics.\n",
    "4. Print the confusion matrix from sklearn.metrics.\n",
    "5. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.\n",
    "\n",
    "Note: Use a random state of 1 for each sampling algorithm to ensure consistency between tests"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "z-f5mGgOdiaf"
   },
   "source": [
    "### Naive Random Oversampling"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 9,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/",
     "height": 34
    },
    "id": "ryGFAn02diag",
    "outputId": "89268c4c-ed24-4372-c12e-0e0a00c99f34"
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Counter({'loan_status': 1})"
      ]
     },
     "execution_count": 9,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Resample the training data with the RandomOversampler\n",
    "from imblearn.over_sampling import RandomOverSampler\n",
    "ros = RandomOverSampler(random_state=1)\n",
    "X_resampled, y_resampled = ros.fit_resample(X_train, y_train)\n",
    "\n",
    "Counter(y_resampled)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 10,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/",
     "height": 102
    },
    "id": "7jRrgK5Kdial",
    "outputId": "132dffe4-e6cd-4349-8b2c-181b63601739"
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "LogisticRegression(random_state=1)"
      ]
     },
     "execution_count": 10,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Train the Logistic Regression model using the resampled data\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "\n",
    "model = LogisticRegression(solver='lbfgs', random_state=1)\n",
    "model.fit(X_resampled, y_resampled)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 11,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/",
     "height": 34
    },
    "id": "e1iJDiffdiar",
    "outputId": "06b82f28-b46f-4831-c992-c018245fd152"
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "0.6503524738582371"
      ]
     },
     "execution_count": 11,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Calculated the balanced accuracy score\n",
    "from sklearn.metrics import balanced_accuracy_score\n",
    "y_pred = model.predict(X_test)\n",
    "balanced_accuracy_score(y_test, y_pred)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/",
     "height": 51
    },
    "id": "u2K6vz1cdiav",
    "outputId": "cecd6bdf-629b-4f05-ce57-f3e3251111c7"
   },
   "outputs": [
    {
     "data": {
      "text/plain": [
       "array([[   70,    31],\n",
       "       [ 6711, 10393]], dtype=int64)"
      ]
     },
     "execution_count": 12,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Display the confusion matrix\n",
    "from sklearn.metrics import confusion_matrix\n",
    "y_pred = model.predict(X_test)\n",
    "confusion_matrix(y_test, y_pred)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/",
     "height": 136
    },
    "id": "eRQTVmYUdia1",
    "outputId": "0240df20-21fc-46be-99df-1115e1c179b3"
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "                   pre       rec       spe        f1       geo       iba       sup\n",
      "\n",
      "  high_risk       0.01      0.69      0.61      0.02      0.65      0.42       101\n",
      "   low_risk       1.00      0.61      0.69      0.76      0.65      0.42     17104\n",
      "\n",
      "avg / total       0.99      0.61      0.69      0.75      0.65      0.42     17205\n",
      "\n"
     ]
    }
   ],
   "source": [
    "# Print the imbalanced classification report\n",
    "from imblearn.metrics import classification_report_imbalanced\n",
    "print(classification_report_imbalanced(y_test, y_pred))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "ZkXdJPfYdia8"
   },
   "source": [
    "### SMOTE Oversampling"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/",
     "height": 34
    },
    "id": "ajJHh7MVdia9",
    "outputId": "bb626a0c-0ba8-4d21-c7ca-e93bb1f67a8c"
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "ERROR:root:\n",
      "UnicodeDecodeError while processing traceback.\n",
      "\n",
      "ERROR:root:\n",
      "UnicodeDecodeError while processing traceback.\n",
      "\n",
      "ERROR:root:\n",
      "UnicodeDecodeError while processing traceback.\n",
      "\n",
      "--- Logging error ---\n",
      "--- Logging error ---\n",
      "--- Logging error ---\n",
      "--- Logging error ---\n",
      "--- Logging error ---\n",
      "Error in sys.excepthook:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\linecache.py\", line 47, in getlines\n",
      "    return updatecache(filename, module_globals)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\linecache.py\", line 137, in updatecache\n",
      "    lines = fp.readlines()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\codecs.py\", line 322, in decode\n",
      "    (result, consumed) = self._buffer_decode(data, self.errors, final)\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0x98 in position 6642: invalid start byte\n",
      "\n",
      "Original exception was:\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3343, in run_code\n",
      "    exec(code_obj, self.user_global_ns, self.user_ns)\n",
      "  File \"<ipython-input-14-6e6da814f53e>\", line 3, in <module>\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\imblearn\\utils\\_validation.py\", line 640, in inner_f\n",
      "TypeError: __init__() got an unexpected keyword argument 'ratio'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3263, in run_ast_nodes\n",
      "    if (await self.run_code(code, result,  async_=asy)):\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3360, in run_code\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2047, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1436, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1336, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1193, in structured_traceback\n",
      "    tb_offset)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2895, in _run_cell\n",
      "    return runner(coro)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 68, in _pseudo_sync_runner\n",
      "    coro.send(None)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3072, in run_cell_async\n",
      "    interactivity=interactivity, compiler=compiler, result=result)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3282, in run_ast_nodes\n",
      "    self.showtraceback()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2047, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1436, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1336, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1211, in structured_traceback\n",
      "    chained_exceptions_tb_offset)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2044, in showtraceback\n",
      "    stb = value._render_traceback_()\n",
      "AttributeError: 'TypeError' object has no attribute '_render_traceback_'\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 268, in dispatch_shell\n",
      "    yield gen.maybe_future(handler(stream, idents, msg))\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\tornado\\gen.py\", line 735, in run\n",
      "    value = future.result()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\tornado\\gen.py\", line 742, in run\n",
      "    yielded = self.gen.throw(*exc_info)  # type: ignore\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 545, in execute_request\n",
      "    user_expressions, allow_stdin,\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\tornado\\gen.py\", line 735, in run\n",
      "    value = future.result()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\tornado\\gen.py\", line 209, in wrapper\n",
      "    yielded = next(result)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 306, in do_execute\n",
      "    res = shell.run_cell(code, store_history=store_history, silent=silent)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 536, in run_cell\n",
      "    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2867, in run_cell\n",
      "    raw_cell, store_history, silent, shell_futures)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2900, in _run_cell\n",
      "    self.showtraceback(running_compiled_code=True)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2047, in showtraceback\n",
      "    value, tb, tb_offset=tb_offset)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1436, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1336, in structured_traceback\n",
      "    self, etype, value, tb, tb_offset, number_of_lines_of_context\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1211, in structured_traceback\n",
      "    chained_exceptions_tb_offset)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 1150, in format_exception_as_a_whole\n",
      "    last_unique, recursion_repeat = find_recursion(orig_etype, evalue, records)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\IPython\\core\\ultratb.py\", line 451, in find_recursion\n",
      "    return len(records), 0\n",
      "TypeError: object of type 'NoneType' has no len()\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\logging\\__init__.py\", line 1025, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\logging\\__init__.py\", line 869, in format\n",
      "    return fmt.format(record)\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\traitlets\\config\\application.py\", line 117, in format\n",
      "    return super(LevelFormatter, self).format(record)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\logging\\__init__.py\", line 616, in format\n",
      "    record.exc_text = self.formatException(record.exc_info)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\logging\\__init__.py\", line 566, in formatException\n",
      "    traceback.print_exception(ei[0], ei[1], tb, None, sio)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 104, in print_exception\n",
      "    type(value), value, tb, limit=limit).format(chain=chain):\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 521, in __init__\n",
      "    self._load_lines()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 533, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 533, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 533, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  [Previous line repeated 3 more times]\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 531, in _load_lines\n",
      "    frame.line\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 285, in line\n",
      "    self._line = linecache.getline(self.filename, self.lineno).strip()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\linecache.py\", line 16, in getline\n",
      "    lines = getlines(filename, module_globals)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\linecache.py\", line 47, in getlines\n",
      "    return updatecache(filename, module_globals)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\linecache.py\", line 137, in updatecache\n",
      "    lines = fp.readlines()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\codecs.py\", line 322, in decode\n",
      "    (result, consumed) = self._buffer_decode(data, self.errors, final)\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0x98 in position 6642: invalid start byte\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 381, in dispatch_queue\n",
      "    yield self.process_one()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\tornado\\gen.py\", line 735, in run\n",
      "    value = future.result()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\tornado\\gen.py\", line 742, in run\n",
      "    yielded = self.gen.throw(*exc_info)  # type: ignore\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 365, in process_one\n",
      "    yield gen.maybe_future(dispatch(*args))\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\tornado\\gen.py\", line 735, in run\n",
      "    value = future.result()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\tornado\\gen.py\", line 742, in run\n",
      "    yielded = self.gen.throw(*exc_info)  # type: ignore\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 270, in dispatch_shell\n",
      "    self.log.error(\"Exception in message handler:\", exc_info=True)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\logging\\__init__.py\", line 1407, in error\n",
      "    self._log(ERROR, msg, args, **kwargs)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\logging\\__init__.py\", line 1514, in _log\n",
      "    self.handle(record)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\logging\\__init__.py\", line 1524, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\logging\\__init__.py\", line 1586, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\logging\\__init__.py\", line 894, in handle\n",
      "    self.emit(record)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\logging\\__init__.py\", line 1033, in emit\n",
      "    self.handleError(record)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\logging\\__init__.py\", line 947, in handleError\n",
      "    traceback.print_exception(t, v, tb, None, sys.stderr)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 104, in print_exception\n",
      "    type(value), value, tb, limit=limit).format(chain=chain):\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 521, in __init__\n",
      "    self._load_lines()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 533, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 533, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 533, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  [Previous line repeated 4 more times]\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 531, in _load_lines\n",
      "    frame.line\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 285, in line\n",
      "    self._line = linecache.getline(self.filename, self.lineno).strip()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\linecache.py\", line 16, in getline\n",
      "    lines = getlines(filename, module_globals)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\linecache.py\", line 47, in getlines\n",
      "    return updatecache(filename, module_globals)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\linecache.py\", line 137, in updatecache\n",
      "    lines = fp.readlines()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\codecs.py\", line 322, in decode\n",
      "    (result, consumed) = self._buffer_decode(data, self.errors, final)\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0x98 in position 6642: invalid start byte\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\logging\\__init__.py\", line 1025, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\logging\\__init__.py\", line 869, in format\n",
      "    return fmt.format(record)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\traitlets\\config\\application.py\", line 117, in format\n",
      "    return super(LevelFormatter, self).format(record)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\logging\\__init__.py\", line 616, in format\n",
      "    record.exc_text = self.formatException(record.exc_info)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\logging\\__init__.py\", line 566, in formatException\n",
      "    traceback.print_exception(ei[0], ei[1], tb, None, sio)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 104, in print_exception\n",
      "    type(value), value, tb, limit=limit).format(chain=chain):\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 521, in __init__\n",
      "    self._load_lines()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 533, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 533, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 533, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  [Previous line repeated 5 more times]\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 531, in _load_lines\n",
      "    frame.line\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 285, in line\n",
      "    self._line = linecache.getline(self.filename, self.lineno).strip()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\linecache.py\", line 16, in getline\n",
      "    lines = getlines(filename, module_globals)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\linecache.py\", line 47, in getlines\n",
      "    return updatecache(filename, module_globals)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\linecache.py\", line 137, in updatecache\n",
      "    lines = fp.readlines()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\codecs.py\", line 322, in decode\n",
      "    (result, consumed) = self._buffer_decode(data, self.errors, final)\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0x98 in position 6642: invalid start byte\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\tornado\\ioloop.py\", line 743, in _run_callback\n",
      "    ret = callback()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\tornado\\ioloop.py\", line 767, in _discard_future_result\n",
      "    future.result()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\tornado\\gen.py\", line 742, in run\n",
      "    yielded = self.gen.throw(*exc_info)  # type: ignore\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 383, in dispatch_queue\n",
      "    self.log.exception(\"Error in message handler\")\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\logging\\__init__.py\", line 1413, in exception\n",
      "    self.error(msg, *args, exc_info=exc_info, **kwargs)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\logging\\__init__.py\", line 1407, in error\n",
      "    self._log(ERROR, msg, args, **kwargs)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\logging\\__init__.py\", line 1514, in _log\n",
      "    self.handle(record)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\logging\\__init__.py\", line 1524, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\logging\\__init__.py\", line 1586, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\logging\\__init__.py\", line 894, in handle\n",
      "    self.emit(record)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\logging\\__init__.py\", line 1033, in emit\n",
      "    self.handleError(record)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\logging\\__init__.py\", line 947, in handleError\n",
      "    traceback.print_exception(t, v, tb, None, sys.stderr)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 104, in print_exception\n",
      "    type(value), value, tb, limit=limit).format(chain=chain):\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 521, in __init__\n",
      "    self._load_lines()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 533, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 533, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 533, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  [Previous line repeated 6 more times]\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 531, in _load_lines\n",
      "    frame.line\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 285, in line\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "    self._line = linecache.getline(self.filename, self.lineno).strip()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\linecache.py\", line 16, in getline\n",
      "    lines = getlines(filename, module_globals)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\linecache.py\", line 47, in getlines\n",
      "    return updatecache(filename, module_globals)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\linecache.py\", line 137, in updatecache\n",
      "    lines = fp.readlines()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\codecs.py\", line 322, in decode\n",
      "    (result, consumed) = self._buffer_decode(data, self.errors, final)\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0x98 in position 6642: invalid start byte\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\logging\\__init__.py\", line 1025, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\logging\\__init__.py\", line 869, in format\n",
      "    return fmt.format(record)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\logging\\__init__.py\", line 616, in format\n",
      "    record.exc_text = self.formatException(record.exc_info)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\logging\\__init__.py\", line 566, in formatException\n",
      "    traceback.print_exception(ei[0], ei[1], tb, None, sio)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 104, in print_exception\n",
      "    type(value), value, tb, limit=limit).format(chain=chain):\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 521, in __init__\n",
      "    self._load_lines()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 533, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 533, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 533, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  [Previous line repeated 7 more times]\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 531, in _load_lines\n",
      "    frame.line\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 285, in line\n",
      "    self._line = linecache.getline(self.filename, self.lineno).strip()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\linecache.py\", line 16, in getline\n",
      "    lines = getlines(filename, module_globals)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\linecache.py\", line 47, in getlines\n",
      "    return updatecache(filename, module_globals)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\linecache.py\", line 137, in updatecache\n",
      "    lines = fp.readlines()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\codecs.py\", line 322, in decode\n",
      "    (result, consumed) = self._buffer_decode(data, self.errors, final)\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0x98 in position 6642: invalid start byte\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\asyncio\\events.py\", line 88, in _run\n",
      "    self._context.run(self._callback, *self._args)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\tornado\\ioloop.py\", line 690, in <lambda>\n",
      "    lambda f: self._run_callback(functools.partial(callback, future))\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\tornado\\ioloop.py\", line 763, in _run_callback\n",
      "    app_log.error(\"Exception in callback %r\", callback, exc_info=True)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\logging\\__init__.py\", line 1407, in error\n",
      "    self._log(ERROR, msg, args, **kwargs)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\logging\\__init__.py\", line 1514, in _log\n",
      "    self.handle(record)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\logging\\__init__.py\", line 1524, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\logging\\__init__.py\", line 1586, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\logging\\__init__.py\", line 894, in handle\n",
      "    self.emit(record)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\logging\\__init__.py\", line 1033, in emit\n",
      "    self.handleError(record)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\logging\\__init__.py\", line 947, in handleError\n",
      "    traceback.print_exception(t, v, tb, None, sys.stderr)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 104, in print_exception\n",
      "    type(value), value, tb, limit=limit).format(chain=chain):\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 521, in __init__\n",
      "    self._load_lines()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 533, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 533, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 533, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  [Previous line repeated 8 more times]\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 531, in _load_lines\n",
      "    frame.line\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 285, in line\n",
      "    self._line = linecache.getline(self.filename, self.lineno).strip()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\linecache.py\", line 16, in getline\n",
      "    lines = getlines(filename, module_globals)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\linecache.py\", line 47, in getlines\n",
      "    return updatecache(filename, module_globals)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\linecache.py\", line 137, in updatecache\n",
      "    lines = fp.readlines()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\codecs.py\", line 322, in decode\n",
      "    (result, consumed) = self._buffer_decode(data, self.errors, final)\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0x98 in position 6642: invalid start byte\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\logging\\__init__.py\", line 1025, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\logging\\__init__.py\", line 869, in format\n",
      "    return fmt.format(record)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\logging\\__init__.py\", line 616, in format\n",
      "    record.exc_text = self.formatException(record.exc_info)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\logging\\__init__.py\", line 566, in formatException\n",
      "    traceback.print_exception(ei[0], ei[1], tb, None, sio)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 104, in print_exception\n",
      "    type(value), value, tb, limit=limit).format(chain=chain):\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 521, in __init__\n",
      "    self._load_lines()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 533, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 533, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 533, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  [Previous line repeated 9 more times]\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 531, in _load_lines\n",
      "    frame.line\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 285, in line\n",
      "    self._line = linecache.getline(self.filename, self.lineno).strip()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\linecache.py\", line 16, in getline\n",
      "    lines = getlines(filename, module_globals)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\linecache.py\", line 47, in getlines\n",
      "    return updatecache(filename, module_globals)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\linecache.py\", line 137, in updatecache\n",
      "    lines = fp.readlines()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\codecs.py\", line 322, in decode\n",
      "    (result, consumed) = self._buffer_decode(data, self.errors, final)\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0x98 in position 6642: invalid start byte\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\asyncio\\base_events.py\", line 1645, in call_exception_handler\n",
      "    self.default_exception_handler(context)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\asyncio\\base_events.py\", line 1619, in default_exception_handler\n",
      "    logger.error('\\n'.join(log_lines), exc_info=exc_info)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\logging\\__init__.py\", line 1407, in error\n",
      "    self._log(ERROR, msg, args, **kwargs)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\logging\\__init__.py\", line 1514, in _log\n",
      "    self.handle(record)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\logging\\__init__.py\", line 1524, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\logging\\__init__.py\", line 1586, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\logging\\__init__.py\", line 894, in handle\n",
      "    self.emit(record)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\logging\\__init__.py\", line 1033, in emit\n",
      "    self.handleError(record)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\logging\\__init__.py\", line 947, in handleError\n",
      "    traceback.print_exception(t, v, tb, None, sys.stderr)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 104, in print_exception\n",
      "    type(value), value, tb, limit=limit).format(chain=chain):\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 521, in __init__\n",
      "    self._load_lines()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 533, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 533, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 533, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  [Previous line repeated 10 more times]\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 531, in _load_lines\n",
      "    frame.line\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 285, in line\n",
      "    self._line = linecache.getline(self.filename, self.lineno).strip()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\linecache.py\", line 16, in getline\n",
      "    lines = getlines(filename, module_globals)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\linecache.py\", line 47, in getlines\n",
      "    return updatecache(filename, module_globals)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\linecache.py\", line 137, in updatecache\n",
      "    lines = fp.readlines()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\codecs.py\", line 322, in decode\n",
      "    (result, consumed) = self._buffer_decode(data, self.errors, final)\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0x98 in position 6642: invalid start byte\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\logging\\__init__.py\", line 1025, in emit\n",
      "    msg = self.format(record)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\logging\\__init__.py\", line 869, in format\n",
      "    return fmt.format(record)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\logging\\__init__.py\", line 616, in format\n",
      "    record.exc_text = self.formatException(record.exc_info)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\logging\\__init__.py\", line 566, in formatException\n",
      "    traceback.print_exception(ei[0], ei[1], tb, None, sio)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 104, in print_exception\n",
      "    type(value), value, tb, limit=limit).format(chain=chain):\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 521, in __init__\n",
      "    self._load_lines()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 533, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 533, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 533, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  [Previous line repeated 11 more times]\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 531, in _load_lines\n",
      "    frame.line\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 285, in line\n",
      "    self._line = linecache.getline(self.filename, self.lineno).strip()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\linecache.py\", line 16, in getline\n",
      "    lines = getlines(filename, module_globals)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\linecache.py\", line 47, in getlines\n",
      "    return updatecache(filename, module_globals)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\linecache.py\", line 137, in updatecache\n",
      "    lines = fp.readlines()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\codecs.py\", line 322, in decode\n",
      "    (result, consumed) = self._buffer_decode(data, self.errors, final)\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0x98 in position 6642: invalid start byte\n",
      "\n",
      "During handling of the above exception, another exception occurred:\n",
      "\n",
      "Traceback (most recent call last):\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\runpy.py\", line 193, in _run_module_as_main\n",
      "    \"__main__\", mod_spec)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\runpy.py\", line 85, in _run_code\n",
      "    exec(code, run_globals)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\ipykernel_launcher.py\", line 16, in <module>\n",
      "    app.launch_new_instance()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\traitlets\\config\\application.py\", line 664, in launch_instance\n",
      "    app.start()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 612, in start\n",
      "    self.io_loop.start()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 149, in start\n",
      "    self.asyncio_loop.run_forever()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\asyncio\\base_events.py\", line 541, in run_forever\n",
      "    self._run_once()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\asyncio\\base_events.py\", line 1786, in _run_once\n",
      "    handle._run()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\asyncio\\events.py\", line 100, in _run\n",
      "    self._loop.call_exception_handler(context)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\asyncio\\base_events.py\", line 1651, in call_exception_handler\n",
      "    exc_info=True)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\logging\\__init__.py\", line 1407, in error\n",
      "    self._log(ERROR, msg, args, **kwargs)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\logging\\__init__.py\", line 1514, in _log\n",
      "    self.handle(record)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\logging\\__init__.py\", line 1524, in handle\n",
      "    self.callHandlers(record)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\logging\\__init__.py\", line 1586, in callHandlers\n",
      "    hdlr.handle(record)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\logging\\__init__.py\", line 894, in handle\n",
      "    self.emit(record)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\logging\\__init__.py\", line 1033, in emit\n",
      "    self.handleError(record)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\logging\\__init__.py\", line 947, in handleError\n",
      "    traceback.print_exception(t, v, tb, None, sys.stderr)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 104, in print_exception\n",
      "    type(value), value, tb, limit=limit).format(chain=chain):\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 521, in __init__\n",
      "    self._load_lines()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 533, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 533, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 533, in _load_lines\n",
      "    self.__context__._load_lines()\n",
      "  [Previous line repeated 12 more times]\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 531, in _load_lines\n",
      "    frame.line\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\traceback.py\", line 285, in line\n",
      "    self._line = linecache.getline(self.filename, self.lineno).strip()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\linecache.py\", line 16, in getline\n",
      "    lines = getlines(filename, module_globals)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\linecache.py\", line 47, in getlines\n",
      "    return updatecache(filename, module_globals)\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\linecache.py\", line 137, in updatecache\n",
      "    lines = fp.readlines()\n",
      "  File \"C:\\Users\\govind_patwal\\Anaconda3\\envs\\mlenv\\lib\\codecs.py\", line 322, in decode\n",
      "    (result, consumed) = self._buffer_decode(data, self.errors, final)\n",
      "UnicodeDecodeError: 'utf-8' codec can't decode byte 0x98 in position 6642: invalid start byte\n"
     ]
    }
   ],
   "source": [
    "# Resample the training data with SMOTE\n",
    "from imblearn.over_sampling import SMOTE\n",
    "X_resampled, y_resampled = SMOTE(random_state=1, ratio=1.0).fit_resample(\n",
    "    X_train, y_train\n",
    ")\n",
    "Counter(y_resampled)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/",
     "height": 102
    },
    "id": "PA82BPKzdibF",
    "outputId": "ae7bc471-b472-441b-bcf8-ea34d31acde3"
   },
   "outputs": [],
   "source": [
    "# Train the Logistic Regression model using the resampled data\n",
    "model = LogisticRegression(solver='lbfgs', random_state=1)\n",
    "model.fit(X_resampled, y_resampled)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/",
     "height": 34
    },
    "id": "7XI0o40LdibJ",
    "outputId": "afd6a1cc-4699-4fbd-b2ac-9d0ef1283469"
   },
   "outputs": [],
   "source": [
    "# Calculated the balanced accuracy score\n",
    "y_pred = model.predict(X_test)\n",
    "balanced_accuracy_score(y_test, y_pred)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/",
     "height": 51
    },
    "id": "Zh63bzYWdibO",
    "outputId": "d0af78a5-5987-47c6-f38c-d74516a4e43c"
   },
   "outputs": [],
   "source": [
    "# Display the confusion matrix\n",
    "confusion_matrix(y_test, y_pred)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/",
     "height": 136
    },
    "id": "C8Nj1wa1dibU",
    "outputId": "6e0f0225-a33e-494c-8438-81a76a86576f"
   },
   "outputs": [],
   "source": [
    "# Print the imbalanced classification report\n",
    "print(classification_report_imbalanced(y_test, y_pred))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "6UAG-Cvkdiba"
   },
   "source": [
    "# Undersampling\n",
    "\n",
    "In this section, you will test an undersampling algorithms to determine which algorithm results in the best performance compared to the oversampling algorithms above. You will undersample the data using the Cluster Centroids algorithm and complete the folliowing steps:\n",
    "\n",
    "1. View the count of the target classes using `Counter` from the collections library. \n",
    "3. Use the resampled data to train a logistic regression model.\n",
    "3. Calculate the balanced accuracy score from sklearn.metrics.\n",
    "4. Print the confusion matrix from sklearn.metrics.\n",
    "5. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.\n",
    "\n",
    "Note: Use a random state of 1 for each sampling algorithm to ensure consistency between tests"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/",
     "height": 34
    },
    "id": "UhF8nSMrdibb",
    "outputId": "442cbdc6-b662-43bb-d30e-5f509c0fe62d"
   },
   "outputs": [],
   "source": [
    "# Resample the data using the ClusterCentroids resampler\n",
    "# Warning: This is a large dataset, and this step may take some time to complete\n",
    "from imblearn.under_sampling import ClusterCentroids\n",
    "cc = ClusterCentroids(random_state=1)\n",
    "X_resampled, y_resampled = cc.fit_resample(X_train, y_train)\n",
    "Counter(y_resampled)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/",
     "height": 102
    },
    "id": "V-Vzd8F8dibg",
    "outputId": "1cabd0dc-32e1-487e-fe4c-8a2121ee0879"
   },
   "outputs": [],
   "source": [
    "# Train the Logistic Regression model using the resampled data\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "model = LogisticRegression(solver='lbfgs', random_state=1)\n",
    "model.fit(X_resampled, y_resampled)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/",
     "height": 34
    },
    "id": "d8TiHwyGdibm",
    "outputId": "d42ff5bc-b628-4a80-e83e-b889704069c5"
   },
   "outputs": [],
   "source": [
    "# Calculated the balanced accuracy score\n",
    "from sklearn.metrics import balanced_accuracy_score\n",
    "y_pred = model.predict(X_test)\n",
    "balanced_accuracy_score(y_test, y_pred)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/",
     "height": 51
    },
    "id": "zRhh8EWkdibq",
    "outputId": "269e2d5a-0fc4-4156-ea81-e7071ebbb3a7"
   },
   "outputs": [],
   "source": [
    "# Display the confusion matrix\n",
    "from sklearn.metrics import confusion_matrix\n",
    "confusion_matrix(y_test, y_pred)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/",
     "height": 136
    },
    "id": "_oVjKvfodibu",
    "outputId": "32dd6592-c04a-4d6f-c2fe-3590a22e1a85"
   },
   "outputs": [],
   "source": [
    "# Print the imbalanced classification report\n",
    "from imblearn.metrics import classification_report_imbalanced\n",
    "print(classification_report_imbalanced(y_test, y_pred))"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {
    "id": "-dI_-Mcfdibz"
   },
   "source": [
    "# Combination (Over and Under) Sampling\n",
    "\n",
    "In this section, you will test a combination over- and under-sampling algorithm to determine if the algorithm results in the best performance compared to the other sampling algorithms above. You will resample the data using the SMOTEENN algorithm and complete the folliowing steps:\n",
    "\n",
    "1. View the count of the target classes using `Counter` from the collections library. \n",
    "3. Use the resampled data to train a logistic regression model.\n",
    "3. Calculate the balanced accuracy score from sklearn.metrics.\n",
    "4. Print the confusion matrix from sklearn.metrics.\n",
    "5. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.\n",
    "\n",
    "Note: Use a random state of 1 for each sampling algorithm to ensure consistency between tests"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/",
     "height": 34
    },
    "id": "8vhWzRbPdib0",
    "outputId": "afb1ba54-95e3-4561-eea5-8808bfefec0e"
   },
   "outputs": [],
   "source": [
    "# Resample the training data with SMOTEENN\n",
    "# Warning: This is a large dataset, and this step may take some time to complete\n",
    "from imblearn.combine import SMOTEENN\n",
    "smote_enn = SMOTEENN(random_state=1)\n",
    "X_resampled, y_resampled = smote_enn.fit_resample(X, y)\n",
    "Counter(y_resampled)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/",
     "height": 102
    },
    "id": "P9j4_tRcdib7",
    "outputId": "a035ad86-8ee3-4ba2-f049-57f6c8b44164"
   },
   "outputs": [],
   "source": [
    "# Train the Logistic Regression model using the resampled data\n",
    "from sklearn.linear_model import LogisticRegression\n",
    "model = LogisticRegression(solver='lbfgs', random_state=1)\n",
    "model.fit(X_resampled, y_resampled)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/",
     "height": 34
    },
    "id": "Yq3tj2zodicA",
    "outputId": "7d70c0d6-93ac-4643-d6fe-ab3ea2ff27a3"
   },
   "outputs": [],
   "source": [
    "# Calculated the balanced accuracy score\n",
    "from sklearn.metrics import balanced_accuracy_score\n",
    "y_pred = model.predict(X_test)\n",
    "balanced_accuracy_score(y_test, y_pred)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/",
     "height": 51
    },
    "id": "QAn1GHGedicI",
    "outputId": "9dc6c63c-3f55-4801-eab9-c2e2775d6af4"
   },
   "outputs": [],
   "source": [
    "# Display the confusion matrix\n",
    "from sklearn.metrics import confusion_matrix\n",
    "confusion_matrix(y_test, y_pred)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "colab": {
     "base_uri": "https://localhost:8080/",
     "height": 136
    },
    "id": "1XIp0IsddicO",
    "outputId": "e00d839c-eef3-4305-b942-198852ab9119"
   },
   "outputs": [],
   "source": [
    "# Print the imbalanced classification report\n",
    "from imblearn.metrics import classification_report_imbalanced\n",
    "print(classification_report_imbalanced(y_test, y_pred))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {
    "id": "8YK773OCdicY"
   },
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "colab": {
   "collapsed_sections": [],
   "name": "D1&D2_credit_risk_resampling.ipynb",
   "provenance": []
  },
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 1
}
